package com.main

enum RacialTrait(racialTrait: String):
  case Strength_2 extends RacialTrait("+2 Strength")
  case Charisma_1 extends RacialTrait("+1 Charisma")
  case Draconic_Ancestry extends RacialTrait("Draconic Ancestry")
  case Breath_Weapon extends RacialTrait("Breath Weapon")
  case Damage_Resistance extends RacialTrait("Damage Resistance")
  case Constitution_2 extends RacialTrait("+2 Constitution")
  case Darkvision extends RacialTrait("Darkvision")
  case Dwarven_Resilience extends RacialTrait("Dwarven Resilience")
  case Dwarven_Combat_Training extends RacialTrait("Dwarven Combat Training")
  case Stonecunning extends RacialTrait("Stonecunning")
  case Dexterity_2 extends RacialTrait("+2 Dexterity")
  case Keen_Senses extends RacialTrait("Keen Senses")
  case Fey_Ancestry extends RacialTrait("Fey Ancestry")
  case Trance extends RacialTrait("Trance")
  case Intelligence_2 extends RacialTrait("+2 Intelligence")
  case Gnome_Cunning extends RacialTrait("Gnome Cunning")
  case Charisma_2 extends RacialTrait("+2 Charisma")
  case Two_Other_Ability_Scores extends RacialTrait("+1 Two Other Ability Scores")
  case Skill_Versatility extends RacialTrait("Skill Versatility")
  case Lucky extends RacialTrait("Lucky")
  case Brave extends RacialTrait("Brave")
  case Halfling_Nimbleness extends RacialTrait("Halfling Nimbleness")
  case Constitution_1 extends RacialTrait("+1 Constitution")
  case Menacing extends RacialTrait("Menacing")
  case Relentless_Endurance extends RacialTrait("Relentless Endurance")
  case Savage_Attacks extends RacialTrait("Savage Attacks")
  case All_Ability_Scores extends RacialTrait("+1 to All Ability Scores")
  case Extra_Language extends RacialTrait("Extra Language")
  case Intelligence_1 extends RacialTrait("+1 Intelligence")
  case Hellish_Resistance extends RacialTrait("Hellish Resistance")
  case Infernal_Legacy extends RacialTrait("Infernal Legacy")
